name: Deploy to EKS

on:
  workflow_dispatch: 

jobs:
  deploy:
    name: Deploy Kubernetes Manifests to AWS EKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup kubeconfig from secret
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        export KUBECONFIG=$HOME/.kube/config

    - name: Apply serviceaccount.yaml
      run: |
        echo "Applying serviceaccount.yaml..."
        kubectl apply -f kubernetes/serviceaccount.yaml

    - name: Deploy all deploy.yaml and svc.yaml recursively
      run: |
        echo "Deploying deploy.yaml and svc.yaml from subdirectories..."
        find kubernetes/ -type f \( -iname 'deploy.yaml' -o -iname 'svc.yaml' \) -exec kubectl apply -f {} \;
